### ISSUE TITLE
Mapa Mental WEB 3.0

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/mapa-mental-web-3-IMA-G#1]
[Mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-IMA-G/files/8386032/Mapa.mental.pdf)

**Comment by Abraham890** [comment]
Calificacion:20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
